### ISSUE TITLE
Initial Intelligent Graph Creation

### ISSUE THREAD

**Issue by deannah** [deannah/tracking-graphs#2]
This code will be the backbone for future graphing efforts, so make sure it is ready to grow.

**Comment by deannah** [comment]
Here are tasks that definitely remain:
- [x] #11 width and height of graph should come from parent container
- [x] #12 graph of Test Spreadsheet should have two areas, not three
- [x] #13 documentation, particularly for Graph, but perhaps everything else too
